name: future_context
description: |
  Cancelable future support.
  'future_context' library is Experimental.
version: 0.0.1+2
homepage: https://github.com/vivitainc/flutter_future_context

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  tuple: ^2.0.0
  async_notify: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
