name: future_context
description: |
  Cancelable future support.
  'future_context' library is Experimental.
version: 0.0.2+13
homepage: https://github.com/vivitainc/flutter_future_context

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  async_notify: ^0.0.2
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
